// Copyright 2023 Danny Nguyen (danny@keeb.io)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define SPLIT_HAND_PIN GP4
#define USB_VBUS_PIN GP8
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13
#define SERIAL_USART_PIN_SWAP
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define I2C_DRIVER I2CD2
#define I2C1_SDA_PIN GP10
#define I2C1_SCL_PIN GP11


// RGB Matrix
#define RGB_MATRIX_LED_COUNT 68
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES


#define SPLIT_LAYER_STATE_ENABLE


//disable effects
#undef LED_MATRIX_SOLID_MULTISPLASH
#undef LED_MATRIX_SOLID_SPLASH
#undef LED_MATRIX_MULTIPLASH
#undef LED_MATRIX_SPLASH
#undef LED_MATRIX_REACTIVE_MULTINEXUS
#undef LED_MATRIX_REACTIVE_NEXUS
#undef LED_MATRIX_REACTIVE_MULTICROSS
#undef LED_MATRIX_REACTIVE_CROSS
#undef LED_MATRIX_REACTIVE_MULTIWIDE
#undef LED_MATRIX_REACTIVE_WIDE
#undef LED_MATRIX_SOLID_REACTIVE
#undef LED_MATRIX_SOLID_REACTIVE_SIMPLE
#undef LED_MATRIX_DIGITAL_RAIN
#undef LED_MATRIX_PIXEL_RAIN
#undef LED_MATRIX_PIXEL_FLOW
#undef LED_MATRIX_PIXEL_FRACTAL
#undef LED_MATRIX_HUE_PENDULUM
#undef LED_MATRIX_HUE_WAVE
#undef LED_MATRIX_HUE_BREATHING
#undef LED_MATRIX_JELLYBEAN_RAINDROPS
#undef LED_MATRIX_RAINDROPS
#undef LED_MATRIX_RAINBOW
#undef LED_MATRIX_CYCLE_PINWHEELS
#undef LED_MATRIX_RAINBOW_BEACON
#undef LED_MATRIX_DUAL_BEACON
#undef LED_MATRIX_CYCLE_SPIRAL
#undef LED_MATRIX_RAINBOW_MOVING_CHEVRON
#undef LED_MATRIX_CYCLE_OUT_IN_DUAL
#undef LED_MATRIX_CYCLE_OUT_IN
#undef LED_MATRIX_ALPHAS_MODS
#undef LED_MATRIX_GRADIENT_UP_DOWN
#undef LED_MATRIX_GRADIENT_LEFT_RIGHT
#undef LED_MATRIX_BREATHING
#undef LED_MATRIX_BAND_SAT
#undef LED_MATRIX_BAND_VAL
#undef LED_MATRIX_BAND_PINWHEEL_SAT
#undef LED_MATRIX_BAND_PINWHEEL_VAL
#undef LED_MATRIX_BAND_SPIRAL_SAT
#undef LED_MATRIX_BAND_SPIRAL_VAL
#undef LED_MATRIX_CYCLE_ALL
#undef LED_MATRIX_CYCLE_LEFT_RIGHT
#undef LED_MATRIX_CYCLE_CYCLE_UP_DOWN




