name: Push To Main
on: [push]
permissions:
  contents: write
jobs:
  build-firmware:
    name: Build Project 🧱
    uses: ./.github/workflows/build-firmware.yaml
    secrets: inherit
    permissions:
      contents: read

  create-visualizer:
    name: Create Visualizer 👀
    needs: [build-firmware]
    uses: ./.github/workflows/create-visualizer.yaml
    secrets: inherit
    permissions:
      contents: write

  create-release:
    name: Create Release 🛫
    runs-on: ubuntu-latest
    needs: [create-visualizer]
    defaults:
      run:
        shell: bash
    steps:
      - name: Download Visualizer Artifact 📥
        uses: actions/download-artifact@v4
        with:
          name:
            visualizer_release_context

      - name: Parse Context
        id: parse_context
        run: |
          ls -l release_context
          cat ${{ github.workspace }}/release_context/release_context | grep yes
          if $?; then
            echo "release=yes" >> $GITHUB_OUTPUT
          else
            echo "release=no" >> $GITHUB_OUTPUT
          fi

      - name: Download Build Artifacts 📥
        if: ${{ steps.parse_context.outputs.release}}
        uses: actions/download-artifact@v4

      - name : Create Tag
        if: ${{ steps.parse_context.outputs.release}}
        id: release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'

      - name: Create Release 🛫
        if: ${{ steps.parse_context.outputs.release}}
        uses: softprops/action-gh-release@67b6c38432c171b8aa64dc6f3f152d12da2d99fa
        with:
          name: ${{ steps.release_tag.outputs.next_release_tag }}
          token: ${{secrets.GITHUB_TOKEN}}
          tag_name: ${{ steps.release_tag.outputs.next_release_tag }}
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/iris-firmware-Love-Pengy/*.uf2
